import os
import sys
import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# Add current dir to path to import MM_DBGDGM
sys.path.append(os.getcwd())

from inference.predict import predict_subject
from visualisation.brain_mapping import plot_brain_projection

# ── Hardcoded Local Paths ───────────────────────────────────────────────────
BASE_DIR = Path(r"h:\Personal\Internships\WeKan\DBGDGM_Improvements")
DATA_DIR = Path(r"C:\WeKan Training Data\mm_dbgdgm_prepared")
MANIFEST_PATH = DATA_DIR / "labels.csv"
CHECKPOINT_PATH = BASE_DIR / "results" / "best_model.pt"
OUTPUT_DIR = BASE_DIR / "inference_reports"
# ─────────────────────────────────────────────────────────────────────────────

def run_subject_inference(subject_id=None):
    """
    Selects a subject from the manifest and generates the clinical report.
    """
    import pandas as pd
    
    # 1. Load Manifest
    if not MANIFEST_PATH.exists():
        print(f"  [Error] Manifest not found at: {MANIFEST_PATH}")
        return
    
    df = pd.read_csv(MANIFEST_PATH)
    
    # 2. Select Subject
    if subject_id:
        sub = df[df['subject_id'] == subject_id]
        if sub.empty:
            print(f"  [Error] Subject {subject_id} not found in manifest.")
            return
        sub = sub.iloc[0]
    else:
        # Default to the first AD subject for demonstration
        ad_subs = df[df['label'] == 2] # 2 is AD in our 3-class setup (CN=0, MCI=1, AD=2)
        if ad_subs.empty:
            sub = df.iloc[0]
        else:
            sub = ad_subs.iloc[0]
    
    subject_id = sub['subject_id']
    fmri_path = DATA_DIR / sub['fmri_path']
    smri_path = DATA_DIR / sub['smri_path']
    
    print(f"\n  Generating report for Subject: {subject_id}")
    generate_report(fmri_path, smri_path, CHECKPOINT_PATH, OUTPUT_DIR / subject_id)

def generate_report(fmri_path, smri_path, checkpoint_path, out_path):
    """
    Runs inference and generates a comprehensive visual report.
    """
    out_path = Path(out_path)
    out_path.mkdir(exist_ok=True, parents=True)
    
    if not checkpoint_path.exists():
        print(f"  [Error] Model weights not found at: {checkpoint_path}")
        print("  Please ensure you have extracted 'best_model.pt' into your results/ folder.")
        return

    # 1. Run Inference
    class_names = ["CN", "MCI", "AD"]
    
    try:
        result = predict_subject(
            fmri_path=fmri_path,
            smri_path=smri_path,
            model_checkpoint=checkpoint_path,
            class_names=class_names
        )
    except Exception as e:
        print(f"  [Error] Inference failed: {e}")
        return

    # 2. Generate Brain Map
    brain_map_path = out_path / "brain_significance_map.png"
    avg_weights = (np.array(result["attention_weights"]["fs"]) + np.array(result["attention_weights"]["sf"])) / 2
    plot_brain_projection(avg_weights, save_path=str(brain_map_path))

    # 3. Create Report Summary Image
    fig = plt.figure(figsize=(12, 13), facecolor='white')
    
    # Use the subject ID from the folder name
    display_id = out_path.name
    
    # Header
    plt.text(0.5, 0.96, "MM-DBGDGM Diagnostic Analysis Report", 
             fontsize=24, fontweight='bold', ha='center')
    plt.text(0.5, 0.93, f"Subject ID: {display_id}", 
             fontsize=14, ha='center', color='gray')
    
    # Prediction Section
    pred_color = '#e74c3c' if result['predicted_class'] == 'AD' else '#3498db'
    plt.text(0.1, 0.86, "Diagnosis Summary:", fontsize=18, fontweight='bold')
    plt.text(0.1, 0.82, "Classification Result:", fontsize=16)
    plt.text(0.4, 0.82, f"{result['predicted_class']}", fontsize=28, fontweight='bold', color=pred_color)
    plt.text(0.65, 0.82, f"Confidence: {result['confidence']:.2%}", fontsize=18)
    
    # Uncertainty Section
    plt.text(0.1, 0.77, "Model Uncertainty Index:", fontsize=16)
    plt.text(0.4, 0.77, f"{result['uncertainty']:.4f}", fontsize=16)
    if result['high_uncertainty_flag']:
        plt.text(0.1, 0.74, "[!] HIGH UNCERTAINTY - Clinical review of structural scans is recommended", 
                 color='red', fontweight='bold', fontsize=11)

    # Brain Map
    plt.text(0.1, 0.69, "Spatial Significance (Affected Brain Regions):", fontsize=16, fontweight='bold')
    brain_img = plt.imread(str(brain_map_path))
    ax_img = fig.add_axes([0.1, 0.28, 0.8, 0.40])
    ax_img.imshow(brain_img)
    ax_img.axis('off')
    
    # Top Regions Text
    plt.text(0.1, 0.24, "Key Contributing Regions:", fontsize=16, fontweight='bold')
    top_5 = result['top_attention_regions'][:5]
    regions_text = "Primary: " + ", ".join(top_5)
    plt.text(0.1, 0.21, regions_text, fontsize=14, color='#34495e')

    # Footer
    plt.text(0.5, 0.05, "Confidential: For Clinical Research Use Only.\nGenerated by MM-DBGDGM v1.0", 
             fontsize=10, ha='center', color='gray', style='italic')

    plt.axis('off')
    report_path = out_path / f"Report_{display_id}.png"
    plt.savefig(report_path, dpi=200, bbox_inches='tight')
    plt.close()
    
    print(f"\n  [Success] Report generated: {report_path}")

if __name__ == "__main__":
    import sys
    # If a subject ID is passed as an argument, use it. Otherwise use default.
    sid = sys.argv[1] if len(sys.argv) > 1 else None
    run_subject_inference(sid)
